### ISSUE TITLE
bug(CLI): Failed to list old environments with the latest envd

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd-server#124]
## Description

The old label looks like:

```
                "ai.tensorchord.envd.pypi.commands": "[\"torch\",\"torchvision\",\"--extra-index-url https://download.pytorch.org/whl/cu113\"]",
```

It does not works with the latest envd since we use `[[], []]` now.

## Additional Info

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by gaocegege** [comment]
Sorry the issue should be in the envd repo.

**Comment by gaocegege** [comment]
I do not think it should work. Just a known issue here.

**Comment by gaocegege** [comment]
I think it works. Since the label is only used to show the packages installed in the environments.

**Comment by kemingy** [comment]
BTW, why do we use "ai.tensorchord.envd.pypi.commands" instead of "ai.tensorchord.envd.pypi.packages"?

**Comment by VoVAllen** [comment]
@kemingy Because if `install.python_packages(['torch', '--index-url xxxxx'])`, `'--index-url xxxxx'` will also be considered as a package

**Comment by kemingy** [comment]
> @kemingy Because if `install.python_packages(['torch', '--index-url xxxxx'])`, `'--index-url xxxxx'` will also be considered as a package

I think it's already fixed in https://github.com/tensorchord/envd/blob/0a416d1a5ad2fef5abecc44beac526ea33511540/pkg/types/envd.go#L326

**Comment by kemingy** [comment]
Oh, I see. It's not fixed.

Shall we filter this when generating the label?

**Comment by VoVAllen** [comment]
I'm not sure whether we can filter all the scenarios. For example, `--index-url xxxx` you need to filter both `---index-url` and `xxxx`, but for `--pre`, you only need to filter out `--pre`. It's complex I think

**Comment by kemingy** [comment]
> I'm not sure whether we can filter all the scenarios. For example, `--index-url xxxx` you need to filter both `---index-url` and `xxxx`, but for `--pre`, you only need to filter out `--pre`. It's complex I think

SGTM. Then shall we remove the filter logic in the code? I think it's not 100% correct.

**Comment by VoVAllen** [comment]
Sure. I think we should remove those logics
