### ISSUE TITLE
feat: Add more info to image and envs

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd-server#132]
## Description

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by kemingy** [comment]
Any details about this issue?

**Comment by VoVAllen** [comment]
@kemingy Currently the package installed is not properly exposed on envd-server through API endpoint. Basically we want to expose everything included in the image label to the API response

**Comment by gaocegege** [comment]
@kemingy Will you work on this issue? Or I could pick it up.

**Comment by kemingy** [comment]
> @kemingy Will you work on this issue? Or I could pick it up.

You can take it.
