### ISSUE TITLE
Envd server timing out when not logged in 

### ISSUE THREAD

**Issue by AlexXi19** [tensorchord/envd-server#163]
The behavior when not logged in (`envd run` without `envd login`) is a bit confusing, ssh'ing into the container times out both on the `run` command or manually ssh'ing into the container. 

![image](https://user-images.githubusercontent.com/68758451/210958359-368ff38b-8124-4b12-ba74-07790f135467.png)

![Screen Shot 2023-01-06 at 12 12 18 AM](https://user-images.githubusercontent.com/68758451/210958462-51131a04-2b5a-4fa5-bb21-069edb4dbf9d.png)

Maybe related to https://github.com/tensorchord/envd-server/issues/160

**Comment by gaocegege** [comment]
Could you please show the log of containerssh?

**Comment by gaocegege** [comment]
And true, we should add a progress bar to envd up and envd run

**Comment by AlexXi19** [comment]
Sorry I stopped using warp so i can only screenshot now lol, let me know if this is enough. 

![image](https://user-images.githubusercontent.com/68758451/210959010-df6d222c-fd47-4b03-9f35-d3f4b7f21d9d.png)

**Comment by gaocegege** [comment]
Yeah sure. BTW may I ask why you stop using warp?

**Comment by gaocegege** [comment]
It looks like ssh key auth failed. We may need to add a warning when users run envd up without login.

**Comment by AlexXi19** [comment]
> Yeah sure. BTW may I ask why you stop using warp?

Going for the tmux + neovim, for terminal applications like these, warp loses all its core features.

**Comment by AlexXi19** [comment]
> This is usually due to the containerssh cannot connect to the pod. Can you check it?

I was able to solve this after logging in.

**Comment by AlexXi19** [comment]
Just from my dev experience, there is definitely quite a few undefined and hard to spot behaviors with login. First one is the one mentioned earlier where it times out on the ssh client creation. And I've also run into problems where the port is not forward correctly. Like below it says that the port is rejected (my sync code depends on the port being forwarded correctly). I was able to fix this after logging in but I'm not sure if the intended behavior is to have the users login before each `run` command or just once for each server. 

![image](https://user-images.githubusercontent.com/68758451/210972241-875e156c-a730-4330-8338-cc9eef6dd940.png)
