### ISSUE TITLE
bug: `image.Size()` always returns -1

### ISSUE THREAD

**Issue by kemingy** [tensorchord/envd-server#55]
`image.Size()` always returns -1. Not sure why.

_Originally posted by @kemingy in https://github.com/tensorchord/envd-server/pull/52#discussion_r1013653506_

**Comment by gaocegege** [comment]
After the investigation, I think we can keep the current implementation. Ref https://github.com/containers/image/blob/0d85878d7a774dd753a4e211455282af94d78556/internal/image/sourced.go#L124
