### ISSUE TITLE
feat: support resource controll

### ISSUE THREAD

**Issue by kemingy** [tensorchord/envd-server#66]
## Description

For the environments in the cluster, we should provide a function to setup the resource:
* CPU
* Memory
* GPU

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by VoVAllen** [comment]
Complex version:
Usually in a well-organized team, there should be templates provided by the admin. In this scenario, user can specify which `pod templates` to be used when launching the envd-server. envd can provide a set of common used templates. Then when user launchs the pod, they'll do `envd up --request 4c8g`, then server will find the template named 4c8g as the pod template when launching the pod. 

Simpler version:
```
envd up --request 4c-8g-1gpu
```
Use `-` to split the resource requirement. In case to support request like `4c-8g-1T4` vs `4c-8g-1V100`

**Comment by gaocegege** [comment]
Should we make it in CLI argument, or introduce a new file, maybe `runtime.envd`?

**Comment by VoVAllen** [comment]
@gaocegege I think in most cases runtime is not fixed, and is subject to change. Thus fixed declaration in file is not flexible enough I think. @kemingy WDYH?

**Comment by kemingy** [comment]
> Should we make it in CLI argument, or introduce a new file, maybe `runtime.envd`?
> 
> ```
> 
> def runtime():
> 
>     setup(cpu=2, memory=4G)
> 
> ```

This looks clearer. I think it would be flexible if it can work with the CLI argument support.
