### ISSUE TITLE
bug: fix muniu bot merge type

### ISSUE THREAD

**Issue by VoVAllen** [tensorchord/envd-server#86]
## Description

I disabled the `merge commits` strategy. `squash merge` should be preferred

## Additional Info

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by gaocegege** [comment]
I can access the prow cluster, but I do not have permission to the ProwJob CRD.

**Comment by kemingy** [comment]
If we don't have complex requirements, we can just use GitHub protected branch rules.

- allow enabling auto-merge
- require at least 1 approval from the code owner

**Comment by gaocegege** [comment]
LGTM.

**Comment by kemingy** [comment]
Seems the bot won't add the "Approved" label.

**Comment by gaocegege** [comment]
This is another issue. Not related to the merge type.

Merge type is already fixed.
